package nl.harm27.obswebsocket.api.events;

import com.fasterxml.jackson.annotation.JsonProperty;

public enum EventType {
    @JsonProperty("SwitchScenes")
    SWITCH_SCENES,
    @JsonProperty("ScenesChanged")
    SCENES_CHANGED,
    @JsonProperty("SceneCollectionChanged")
    SCENE_COLLECTION_CHANGED,
    @JsonProperty("SceneCollectionListChanged")
    SCENE_COLLECTION_LIST_CHANGED,
    @JsonProperty("SwitchTransition")
    SWITCH_TRANSITION,
    @JsonProperty("TransitionListChanged")
    TRANSITION_LIST_CHANGED,
    @JsonProperty("TransitionDurationChanged")
    TRANSITION_DURATION_CHANGED,
    @JsonProperty("TransitionBegin")
    TRANSITION_BEGIN,
    @JsonProperty("ProfileChanged")
    PROFILE_CHANGED,
    @JsonProperty("ProfileListChanged")
    PROFILE_LIST_CHANGED,
    @JsonProperty("StreamStarting")
    STREAM_STARTING,
    @JsonProperty("StreamStarted")
    STREAM_STARTED,
    @JsonProperty("StreamStopping")
    STREAM_STOPPING,
    @JsonProperty("StreamStopped")
    STREAM_STOPPED,
    @JsonProperty("StreamStatus")
    STREAM_STATUS,
    @JsonProperty("RecordingStarting")
    RECORDING_STARTING,
    @JsonProperty("RecordingStarted")
    RECORDING_STARTED,
    @JsonProperty("RecordingStopping")
    RECORDING_STOPPING,
    @JsonProperty("RecordingStopped")
    RECORDING_STOPPED,
    @JsonProperty("RecordingPaused")
    RECORDING_PAUSED,
    @JsonProperty("RecordingResumed")
    RECORDING_RESUMED,
    @JsonProperty("ReplayStarting")
    REPLAY_STARTING,
    @JsonProperty("ReplayStarted")
    REPLAY_STARTED,
    @JsonProperty("ReplayStopping")
    REPLAY_STOPPING,
    @JsonProperty("ReplayStopped")
    REPLAY_STOPPED,
    @JsonProperty("Exiting")
    EXITING,
    @JsonProperty("Heartbeat")
    HEARTBEAT,
    @JsonProperty("BroadcastCustomMessage")
    BROADCAST_CUSTOM_MESSAGE,
    @JsonProperty("SourceCreated")
    SOURCE_CREATED,
    @JsonProperty("SourceDestroyed")
    SOURCE_DESTROYED,
    @JsonProperty("SourceVolumeChanged")
    SOURCE_VOLUME_CHANGED,
    @JsonProperty("SourceMuteStateChanged")
    SOURCE_MUTE_STATE_CHANGED,
    @JsonProperty("SourceAudioSyncOffsetChanged")
    SOURCE_AUDIO_SYNC_OFFSET_CHANGED,
    @JsonProperty("SourceAudioMixersChanged")
    SOURCE_AUDIO_MIXERS_CHANGED,
    @JsonProperty("SourceRenamed")
    SOURCE_RENAMED,
    @JsonProperty("SourceFilterAdded")
    SOURCE_FILTER_ADDED,
    @JsonProperty("SourceFilterRemoved")
    SOURCE_FILTER_REMOVED,
    @JsonProperty("SourceFilterVisibilityChanged")
    SOURCE_FILTER_VISIBILITY_CHANGED,
    @JsonProperty("SourceFiltersReordered")
    SOURCE_FILTERS_REORDERED,
    @JsonProperty("SourceOrderChanged")
    SOURCE_ORDER_CHANGED,
    @JsonProperty("SceneItemAdded")
    SCENE_ITEM_ADDED,
    @JsonProperty("SceneItemRemoved")
    SCENE_ITEM_REMOVED,
    @JsonProperty("SceneItemVisibilityChanged")
    SCENE_ITEM_VISIBILITY_CHANGED,
    @JsonProperty("SceneItemTransformChanged")
    SCENE_ITEM_TRANSFORM_CHANGED,
    @JsonProperty("SceneItemSelected")
    SCENE_ITEM_SELECTED,
    @JsonProperty("SceneItemDeselected")
    SCENE_ITEM_DESELECTED,
    @JsonProperty("PreviewSceneChanged")
    PREVIEW_SCENE_CHANGED,
    @JsonProperty("StudioModeSwitched")
    STUDIO_MODE_SWITCHED
}
