package nl.harm27.obswebsocket.api.events;

import com.google.gson.annotations.SerializedName;

public enum EventType {
    @SerializedName("SwitchScenes")
    SWITCH_SCENES,
    @SerializedName("ScenesChanged")
    SCENES_CHANGED,
    @SerializedName("SceneCollectionChanged")
    SCENE_COLLECTION_CHANGED,
    @SerializedName("SceneCollectionListChanged")
    SCENE_COLLECTION_LIST_CHANGED,
    @SerializedName("SwitchTransition")
    SWITCH_TRANSITION,
    @SerializedName("TransitionListChanged")
    TRANSITION_LIST_CHANGED,
    @SerializedName("TransitionDurationChanged")
    TRANSITION_DURATION_CHANGED,
    @SerializedName("TransitionBegin")
    TRANSITION_BEGIN,
    @SerializedName("ProfileChanged")
    PROFILE_CHANGED,
    @SerializedName("ProfileListChanged")
    PROFILE_LIST_CHANGED,
    @SerializedName("StreamStarting")
    STREAM_STARTING,
    @SerializedName("StreamStarted")
    STREAM_STARTED,
    @SerializedName("StreamStopping")
    STREAM_STOPPING,
    @SerializedName("StreamStopped")
    STREAM_STOPPED,
    @SerializedName("StreamStatus")
    STREAM_STATUS,
    @SerializedName("RecordingStarting")
    RECORDING_STARTING,
    @SerializedName("RecordingStarted")
    RECORDING_STARTED,
    @SerializedName("RecordingStopping")
    RECORDING_STOPPING,
    @SerializedName("RecordingStopped")
    RECORDING_STOPPED,
    @SerializedName("RecordingPaused")
    RECORDING_PAUSED,
    @SerializedName("RecordingResumed")
    RECORDING_RESUMED,
    @SerializedName("ReplayStarting")
    REPLAY_STARTING,
    @SerializedName("ReplayStarted")
    REPLAY_STARTED,
    @SerializedName("ReplayStopping")
    REPLAY_STOPPING,
    @SerializedName("ReplayStopped")
    REPLAY_STOPPED,
    @SerializedName("Exiting")
    EXITING,
    @SerializedName("Heartbeat")
    HEARTBEAT,
    @SerializedName("BroadcastCustomMessage")
    BROADCAST_CUSTOM_MESSAGE,
    @SerializedName("SourceCreated")
    SOURCE_CREATED,
    @SerializedName("SourceDestroyed")
    SOURCE_DESTROYED,
    @SerializedName("SourceVolumeChanged")
    SOURCE_VOLUME_CHANGED,
    @SerializedName("SourceMuteStateChanged")
    SOURCE_MUTE_STATE_CHANGED,
    @SerializedName("SourceAudioSyncOffsetChanged")
    SOURCE_AUDIO_SYNC_OFFSET_CHANGED,
    @SerializedName("SourceAudioMixersChanged")
    SOURCE_AUDIO_MIXERS_CHANGED,
    @SerializedName("SourceRenamed")
    SOURCE_RENAMED,
    @SerializedName("SourceFilterAdded")
    SOURCE_FILTER_ADDED,
    @SerializedName("SourceFilterRemoved")
    SOURCE_FILTER_REMOVED,
    @SerializedName("SourceFilterVisibilityChanged")
    SOURCE_FILTER_VISIBILITY_CHANGED,
    @SerializedName("SourceFiltersReordered")
    SOURCE_FILTERS_REORDERED,
    @SerializedName("SourceOrderChanged")
    SOURCE_ORDER_CHANGED,
    @SerializedName("SceneItemAdded")
    SCENE_ITEM_ADDED,
    @SerializedName("SceneItemRemoved")
    SCENE_ITEM_REMOVED,
    @SerializedName("SceneItemVisibilityChanged")
    SCENE_ITEM_VISIBILITY_CHANGED,
    @SerializedName("SceneItemTransformChanged")
    SCENE_ITEM_TRANSFORM_CHANGED,
    @SerializedName("SceneItemSelected")
    SCENE_ITEM_SELECTED,
    @SerializedName("SceneItemDeselected")
    SCENE_ITEM_DESELECTED,
    @SerializedName("PreviewSceneChanged")
    PREVIEW_SCENE_CHANGED,
    @SerializedName("StudioModeSwitched")
    STUDIO_MODE_SWITCHED
}
