package nl.harm27.obswebsocket.api.requests;

import com.fasterxml.jackson.annotation.JsonProperty;

public enum RequestType {
    @JsonProperty("GetVersion")
    GET_VERSION,
    @JsonProperty("GetAuthRequired")
    GET_AUTH_REQUIRED,
    @JsonProperty("Authenticate")
    AUTHENTICATE,
    @JsonProperty("SetHeartbeat")
    SET_HEARTBEAT,
    @JsonProperty("SetFilenameFormatting")
    SET_FILENAME_FORMATTING,
    @JsonProperty("GetFilenameFormatting")
    GET_FILENAME_FORMATTING,
    @JsonProperty("GetStats")
    GET_STATS,
    @JsonProperty("BroadcastCustomMessage")
    BROADCAST_CUSTOM_MESSAGE,
    @JsonProperty("GetVideoInfo")
    GET_VIDEO_INFO,
    @JsonProperty("OpenProjector")
    OPEN_PROJECTOR,
    @JsonProperty("ListOutputs")
    LIST_OUTPUTS,
    @JsonProperty("GetOutputInfo")
    GET_OUTPUT_INFO,
    @JsonProperty("StartOutput")
    START_OUTPUT,
    @JsonProperty("StopOutput")
    STOP_OUTPUT,
    @JsonProperty("SetCurrentProfile")
    SET_CURRENT_PROFILE,
    @JsonProperty("GetCurrentProfile")
    GET_CURRENT_PROFILE,
    @JsonProperty("ListProfiles")
    LIST_PROFILES,
    @JsonProperty("StartStopRecording")
    START_STOP_RECORDING,
    @JsonProperty("StartRecording")
    START_RECORDING,
    @JsonProperty("StopRecording")
    STOP_RECORDING,
    @JsonProperty("PauseRecording")
    PAUSE_RECORDING,
    @JsonProperty("ResumeRecording")
    RESUME_RECORDING,
    @JsonProperty("SetRecordingFolder")
    SET_RECORDING_FOLDER,
    @JsonProperty("GetRecordingFolder")
    GET_RECORDING_FOLDER,
    @JsonProperty("StartStopReplayBuffer")
    START_STOP_REPLAY_BUFFER,
    @JsonProperty("StartReplayBuffer")
    START_REPLAY_BUFFER,
    @JsonProperty("StopReplayBuffer")
    STOP_REPLAY_BUFFER,
    @JsonProperty("SaveReplayBuffer")
    SAVE_REPLAY_BUFFER,
    @JsonProperty("SetCurrentSceneCollection")
    SET_CURRENT_SCENE_COLLECTION,
    @JsonProperty("GetCurrentSceneCollection")
    GET_CURRENT_SCENE_COLLECTION,
    @JsonProperty("ListSceneCollections")
    LIST_SCENE_COLLECTIONS,
    @JsonProperty("GetSceneItemProperties")
    GET_SCENE_ITEM_PROPERTIES,
    @JsonProperty("SetSceneItemProperties")
    SET_SCENE_ITEM_PROPERTIES,
    @JsonProperty("ResetSceneItem")
    RESET_SCENE_ITEM,
    @JsonProperty("SetSceneItemRender")
    SET_SCENE_ITEM_RENDER,
    @JsonProperty("SetSceneItemPosition")
    SET_SCENE_ITEM_POSITION,
    @JsonProperty("SetSceneItemTransform")
    SET_SCENE_ITEM_TRANSFORM,
    @JsonProperty("SetSceneItemCrop")
    SET_SCENE_ITEM_CROP,
    @JsonProperty("DeleteSceneItem")
    DELETE_SCENE_ITEM,
    @JsonProperty("DuplicateSceneItem")
    DUPLICATE_SCENE_ITEM,
    @JsonProperty("SetCurrentScene")
    SET_CURRENT_SCENE,
    @JsonProperty("GetCurrentScene")
    GET_CURRENT_SCENE,
    @JsonProperty("GetSceneList")
    GET_SCENE_LIST,
    @JsonProperty("ReorderSceneItems")
    REORDER_SCENE_ITEMS,
    @JsonProperty("GetSourcesList")
    GET_SOURCES_LIST,
    @JsonProperty("GetSourceTypesList")
    GET_SOURCE_TYPES_LIST,
    @JsonProperty("GetVolume")
    GET_VOLUME,
    @JsonProperty("SetVolume")
    SET_VOLUME,
    @JsonProperty("GetMute")
    GET_MUTE,
    @JsonProperty("SetMute")
    SET_MUTE,
    @JsonProperty("ToggleMute")
    TOGGLE_MUTE,
    @JsonProperty("SetSyncOffset")
    SET_SYNC_OFFSET,
    @JsonProperty("GetSyncOffset")
    GET_SYNC_OFFSET,
    @JsonProperty("GetSourceSettings")
    GET_SOURCE_SETTINGS,
    @JsonProperty("SetSourceSettings")
    SET_SOURCE_SETTINGS,
    @JsonProperty("GetTextGDIPlusProperties")
    GET_TEXT_GDI_PLUS_PROPERTIES,
    @JsonProperty("SetTextGDIPlusProperties")
    SET_TEXT_GDI_PLUS_PROPERTIES,
    @JsonProperty("GetTextFreetype2Properties")
    GET_TEXT_FREE_TYPE_2_PROPERTIES,
    @JsonProperty("SetTextFreetype2Properties")
    SET_TEXT_FREE_TYPE_2_PROPERTIES,
    @JsonProperty("GetBrowserSourceProperties")
    GET_BROWSER_SOURCE_PROPERTIES,
    @JsonProperty("SetBrowserSourceProperties")
    SET_BROWSER_SOURCE_PROPERTIES,
    @JsonProperty("GetSpecialSources")
    GET_SPECIAL_SOURCES,
    @JsonProperty("GetSourceFilters")
    GET_SOURCE_FILTERS,
    @JsonProperty("GetSourceFilterInfo")
    GET_SOURCE_FILTER_INFO,
    @JsonProperty("AddFilterToSource")
    ADD_FILTER_TO_SOURCE,
    @JsonProperty("RemoveFilterFromSource")
    REMOVE_FILTER_FROM_SOURCE,
    @JsonProperty("ReorderSourceFilter")
    REORDER_SOURCE_FILTER,
    @JsonProperty("MoveSourceFilter")
    MOVE_SOURCE_FILTER,
    @JsonProperty("SetSourceFilterSettings")
    SET_SOURCE_FILTER_SETTINGS,
    @JsonProperty("SetSourceFilterVisibility")
    SET_SOURCE_FILTER_VISIBILITY,
    @JsonProperty("TakeSourceScreenshot")
    TAKE_SOURCE_SCREENSHOT,
    @JsonProperty("GetStreamingStatus")
    GET_STREAMING_STATUS,
    @JsonProperty("StartStopStreaming")
    START_STOP_STREAMING,
    @JsonProperty("StartStreaming")
    START_STREAMING,
    @JsonProperty("StopStreaming")
    STOP_STREAMING,
    @JsonProperty("SetStreamSettings")
    SET_STREAM_SETTINGS,
    @JsonProperty("GetStreamSettings")
    GET_STREAM_SETTINGS,
    @JsonProperty("SaveStreamSettings")
    SAVE_STREAM_SETTINGS,
    @JsonProperty("SendCaptions")
    SEND_CAPTIONS,
    @JsonProperty("GetStudioModeStatus")
    GET_STUDIO_MODE_STATUS,
    @JsonProperty("GetPreviewScene")
    GET_PREVIEW_SCENE,
    @JsonProperty("SetPreviewScene")
    SET_PREVIEW_SCENE,
    @JsonProperty("TransitionToProgram")
    TRANSITION_TO_PROGRAM,
    @JsonProperty("EnableStudioMode")
    ENABLE_STUDIO_MODE,
    @JsonProperty("DisableStudioMode")
    DISABLE_STUDIO_MODE,
    @JsonProperty("ToggleStudioMode")
    TOGGLE_STUDIO_MODE,
    @JsonProperty("GetTransitionList")
    GET_TRANSITION_LIST,
    @JsonProperty("GetCurrentTransition")
    GET_CURRENT_TRANSITION,
    @JsonProperty("SetCurrentTransition")
    SET_CURRENT_TRANSITION,
    @JsonProperty("SetTransitionDuration")
    SET_TRANSITION_DURATION,
    @JsonProperty("GetTransitionDuration")
    GET_TRANSITION_DURATION
}
