package nl.harm27.obswebsocket.api.requests;

import com.google.gson.annotations.SerializedName;

public enum RequestType {
    @SerializedName("GetVersion")
    GET_VERSION,
    @SerializedName("GetAuthRequired")
    GET_AUTH_REQUIRED,
    @SerializedName("Authenticate")
    AUTHENTICATE,
    @SerializedName("SetHeartbeat")
    SET_HEARTBEAT,
    @SerializedName("SetFilenameFormatting")
    SET_FILENAME_FORMATTING,
    @SerializedName("GetFilenameFormatting")
    GET_FILENAME_FORMATTING,
    @SerializedName("GetStats")
    GET_STATS,
    @SerializedName("BroadcastCustomMessage")
    BROADCAST_CUSTOM_MESSAGE,
    @SerializedName("GetVideoInfo")
    GET_VIDEO_INFO,
    @SerializedName("OpenProjector")
    OPEN_PROJECTOR,
    @SerializedName("ListOutputs")
    LIST_OUTPUTS,
    @SerializedName("GetOutputInfo")
    GET_OUTPUT_INFO,
    @SerializedName("StartOutput")
    START_OUTPUT,
    @SerializedName("StopOutput")
    STOP_OUTPUT,
    @SerializedName("SetCurrentProfile")
    SET_CURRENT_PROFILE,
    @SerializedName("GetCurrentProfile")
    GET_CURRENT_PROFILE,
    @SerializedName("ListProfiles")
    LIST_PROFILES,
    @SerializedName("StartStopRecording")
    START_STOP_RECORDING,
    @SerializedName("StartRecording")
    START_RECORDING,
    @SerializedName("StopRecording")
    STOP_RECORDING,
    @SerializedName("PauseRecording")
    PAUSE_RECORDING,
    @SerializedName("ResumeRecording")
    RESUME_RECORDING,
    @SerializedName("SetRecordingFolder")
    SET_RECORDING_FOLDER,
    @SerializedName("GetRecordingFolder")
    GET_RECORDING_FOLDER,
    @SerializedName("StartStopReplayBuffer")
    START_STOP_REPLAY_BUFFER,
    @SerializedName("StartReplayBuffer")
    START_REPLAY_BUFFER,
    @SerializedName("StopReplayBuffer")
    STOP_REPLAY_BUFFER,
    @SerializedName("SaveReplayBuffer")
    SAVE_REPLAY_BUFFER,
    @SerializedName("SetCurrentSceneCollection")
    SET_CURRENT_SCENE_COLLECTION,
    @SerializedName("GetCurrentSceneCollection")
    GET_CURRENT_SCENE_COLLECTION,
    @SerializedName("ListSceneCollections")
    LIST_SCENE_COLLECTIONS,
    @SerializedName("GetSceneItemProperties")
    GET_SCENE_ITEM_PROPERTIES,
    @SerializedName("SetSceneItemProperties")
    SET_SCENE_ITEM_PROPERTIES,
    @SerializedName("ResetSceneItem")
    RESET_SCENE_ITEM,
    @SerializedName("SetSceneItemRender")
    SET_SCENE_ITEM_RENDER,
    @SerializedName("SetSceneItemPosition")
    SET_SCENE_ITEM_POSITION,
    @SerializedName("SetSceneItemTransform")
    SET_SCENE_ITEM_TRANSFORM,
    @SerializedName("SetSceneItemCrop")
    SET_SCENE_ITEM_CROP,
    @SerializedName("DeleteSceneItem")
    DELETE_SCENE_ITEM,
    @SerializedName("DuplicateSceneItem")
    DUPLICATE_SCENE_ITEM,
    @SerializedName("SetCurrentScene")
    SET_CURRENT_SCENE,
    @SerializedName("GetCurrentScene")
    GET_CURRENT_SCENE,
    @SerializedName("GetSceneList")
    GET_SCENE_LIST,
    @SerializedName("ReorderSceneItems")
    REORDER_SCENE_ITEMS,
    @SerializedName("GetSourcesList")
    GET_SOURCES_LIST,
    @SerializedName("GetSourceTypesList")
    GET_SOURCE_TYPES_LIST,
    @SerializedName("GetVolume")
    GET_VOLUME,
    @SerializedName("SetVolume")
    SET_VOLUME,
    @SerializedName("GetMute")
    GET_MUTE,
    @SerializedName("SetMute")
    SET_MUTE,
    @SerializedName("ToggleMute")
    TOGGLE_MUTE,
    @SerializedName("SetSyncOffset")
    SET_SYNC_OFFSET,
    @SerializedName("GetSyncOffset")
    GET_SYNC_OFFSET,
    @SerializedName("GetSourceSettings")
    GET_SOURCE_SETTINGS,
    @SerializedName("SetSourceSettings")
    SET_SOURCE_SETTINGS,
    @SerializedName("GetTextGDIPlusProperties")
    GET_TEXT_GDI_PLUS_PROPERTIES,
    @SerializedName("SetTextGDIPlusProperties")
    SET_TEXT_GDI_PLUS_PROPERTIES,
    @SerializedName("GetTextFreetype2Properties")
    GET_TEXT_FREE_TYPE_2_PROPERTIES,
    @SerializedName("SetTextFreetype2Properties")
    SET_TEXT_FREE_TYPE_2_PROPERTIES,
    @SerializedName("GetBrowserSourceProperties")
    GET_BROWSER_SOURCE_PROPERTIES,
    @SerializedName("SetBrowserSourceProperties")
    SET_BROWSER_SOURCE_PROPERTIES,
    @SerializedName("GetSpecialSources")
    GET_SPECIAL_SOURCES,
    @SerializedName("GetSourceFilters")
    GET_SOURCE_FILTERS,
    @SerializedName("GetSourceFilterInfo")
    GET_SOURCE_FILTER_INFO,
    @SerializedName("AddFilterToSource")
    ADD_FILTER_TO_SOURCE,
    @SerializedName("RemoveFilterFromSource")
    REMOVE_FILTER_FROM_SOURCE,
    @SerializedName("ReorderSourceFilter")
    REORDER_SOURCE_FILTER,
    @SerializedName("MoveSourceFilter")
    MOVE_SOURCE_FILTER,
    @SerializedName("SetSourceFilterSettings")
    SET_SOURCE_FILTER_SETTINGS,
    @SerializedName("SetSourceFilterVisibility")
    SET_SOURCE_FILTER_VISIBILITY,
    @SerializedName("TakeSourceScreenshot")
    TAKE_SOURCE_SCREENSHOT,
    @SerializedName("GetStreamingStatus")
    GET_STREAMING_STATUS,
    @SerializedName("StartStopStreaming")
    START_STOP_STREAMING,
    @SerializedName("StartStreaming")
    START_STREAMING,
    @SerializedName("StopStreaming")
    STOP_STREAMING,
    @SerializedName("SetStreamSettings")
    SET_STREAM_SETTINGS,
    @SerializedName("GetStreamSettings")
    GET_STREAM_SETTINGS,
    @SerializedName("SaveStreamSettings")
    SAVE_STREAM_SETTINGS,
    @SerializedName("SendCaptions")
    SEND_CAPTIONS,
    @SerializedName("GetStudioModeStatus")
    GET_STUDIO_MODE_STATUS,
    @SerializedName("GetPreviewScene")
    GET_PREVIEW_SCENE,
    @SerializedName("SetPreviewScene")
    SET_PREVIEW_SCENE,
    @SerializedName("TransitionToProgram")
    TRANSITION_TO_PROGRAM,
    @SerializedName("EnableStudioMode")
    ENABLE_STUDIO_MODE,
    @SerializedName("DisableStudioMode")
    DISABLE_STUDIO_MODE,
    @SerializedName("ToggleStudioMode")
    TOGGLE_STUDIO_MODE,
    @SerializedName("GetTransitionList")
    GET_TRANSITION_LIST,
    @SerializedName("GetCurrentTransition")
    GET_CURRENT_TRANSITION,
    @SerializedName("SetCurrentTransition")
    SET_CURRENT_TRANSITION,
    @SerializedName("SetTransitionDuration")
    SET_TRANSITION_DURATION,
    @SerializedName("GetTransitionDuration")
    GET_TRANSITION_DURATION
}
