name: Auto-Create branch

on: 
  issues:
    types: [labeled]

jobs:
  branch:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Debugging
      run: 
        echo Debug ${{github.event.issue.label }}
        echo Debug ${{github.event.label.name }}
