name: Master Build

issues:
    types: [labeled]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 
      run: echo Debug {{  github.event.label.name }}
