name: Auto-Create branch

on: 
  issues:
    types: [labeled]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Debugging
      env:
        label: ${{github.event.issue.label.name }}
      run: echo Debug {{env.label}}
