name: Javadoc to Github Pages

on:
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Generate Javadoc
      run: mvn -B javadoc:javadoc --file pom.xml

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ github.token }}
        BRANCH: gh-pages
        FOLDER: target/apidocs
