name: Automated label actions

on: 
  issues:
    types: [labeled]

jobs:
  branch:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'in-development'

    steps:
    - uses: actions/checkout@v2

    - name: Create branch
      uses: peterjgrainger/action-create-branch@v1.0.0
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: 'issue/${{github.event.issue.number }}'

  pr:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'ready'

    steps:
    - uses: actions/checkout@v2

    - name: Debugging
      run: 
        echo Debug ${{github.event.issue.number }}
