name: Master Build

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v2.1.1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Get maven version
        run: ${mvn help:evaluate -Dexpression=project.version -q -DforceStdout/'-SNAPSHOT'/$EPOCHSECONDS}
      - name: Build with Maven
        run: mvn -B install --file pom.xml
      - name: Generate Javadoc
        run: mvn -B javadoc:aggregate --file pom.xml
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.JAVADOC_GITHUB_PAGES }}
          BRANCH: gh-pages
          FOLDER: target/site/apidocs
          TARGET_FOLDER: snapshot

  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v2.1.1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: SonarCloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn verify sonar:sonar -Dsonar.login=${{secrets.SONAR_LOGIN}} -DskipTests=true -Dmaven.javadoc.skip=true
