name: Milestone actions

on:
  milestone:
    types: [closed]

jobs:
  setversion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Update version
        run: mvn -B mvn versions:set -DnewVersion=${{github.event.title }} --file pom.xml
      - name: Commit version change
        run: |
          git add .
          git commit -m "Updated to version ${{github.event.title }}"
          git tag v${{github.event.title }}
          git push --tags
