name: Nightly Build

#on:
#  schedule:
#    - cron: 0 0 * * *
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Get Maven version
        run: echo PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) >> $GITHUB_ENV
      - name: Replace -SNAPSHOT
        uses: frabert/replace-string-action@v1.2
        with:
          pattern: '(\d\.\d)'
          string: ${{ env.PROJECT_VERSION}}
          replace-with: '$1-NIGHTLY-${GITHUB-RUN-NUMBER}'
      - name: Echo Project version
        run: echo ${{ env.PROJECT_VERSION }}
      #      - name: Convert Maven version
      #        run: echo TARGET_VERSION=${PROJECT_VERSION}-NIGHTLY-${GITHUB_RUN_NUMBER} >> $GITHUB_ENV
      #      - name: Update version
      #        run: mvn -B versions:set -DnewVersion=${{ env.TARGET_VERSION }} --file pom.xml
      - name: Build with Maven
        run: mvn -B package --file pom.xml