name: Nightly Build

on:
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v2.1.2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Get Maven version
        run: echo PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) >> $GITHUB_ENV
      - name: Convert Maven version
        id: version
        uses: ashley-taylor/regex-property-action@1.2
        with:
          value: ${{ env.PROJECT_VERSION }}
          regex: "(SNAPSHOT)"
          replacement: "NIGHTLY-${GITHUB_RUN_NUMBER}"
      - name: Update version
        run: mvn -B versions:set -DnewVersion=${{ steps.version.outputs.value }} --file pom.xml
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -pl websocket-client
        env:
          GITHUB_TOKEN: ${{ github.token }}