name: Automated label actions

on: 
  issues:
    types: [unlabeled]

jobs:
  branch:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'in-development'

    steps:
    - uses: actions/checkout@v2
    - name: Delete branch
      uses: dawidd6/action-delete-branch@v3
      with:
        github_token: ${{github.token}}
        branches: 'issue/${{github.event.issue.number }}'
